[package]
name = "rust_websocket_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "0.1"
tokio-tungstenite = "0.6.0" # Check for the latest version
futures-util = { version = "0.3", features = ["sink"] }
